# Generated by Django 3.2 on 2025-11-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chichewa', models.CharField(max_length=100)),
                ('english', models.CharField(max_length=100)),
                ('scientific', models.CharField(max_length=100)),
            ],
        ),
    ]
