# Generated by Django 4.0.5 on 2025-07-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('region', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('capital', models.CharField(max_length=100, null=True)),
                ('population_2023', models.IntegerField()),
                ('area_km2', models.FloatField()),
                ('density', models.FloatField()),
                ('elevation_m', models.IntegerField()),
                ('climate', models.CharField(max_length=100)),
                ('timezone', models.CharField(max_length=50)),
            ],
        ),
    ]
