# Generated by Django 5.2.4 on 2025-09-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='languages',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
