# Generated by Django 3.2 on 2025-11-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Healthdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('health_centers', models.CharField(max_length=100)),
                ('hospitals', models.CharField(max_length=100)),
                ('dispensaries', models.CharField(max_length=100)),
            ],
        ),
    ]
