# Generated by Django 3.2 on 2025-11-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdata',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
