# Generated by Django 4.0.5 on 2025-07-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chichewa', models.CharField(max_length=100)),
                ('english', models.CharField(max_length=100)),
                ('scientific', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chichewa', models.CharField(max_length=100)),
                ('english', models.CharField(max_length=100)),
                ('scientific', models.CharField(max_length=100)),
            ],
        ),
    ]
